name: Validate proposals with swift-evolution-metadata-extractor

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - 'main'
#    paths:
#      - 'proposals/*'

jobs:
  validate:
    name: Validate Proposals
    uses: ./.github/workflows/proposal_validation.yml
    with:
      project: "swift"
