name: Validate proposals with swift-evolution-metadata-extractor

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main

jobs:
  run-swift-evolution-metadata-extractor:
    name: Validate proposals with swift-evolution-metadata-extractor
    runs-on: macos-latest
    steps:

      - name: Test PR Number Value  
        run: |  
          EVENT_NUMBER=${github.event.number}
          PR_NUMBER=${github.event.pull_request_number}  
          echo "Event Number: $EVENT_NUMBER"
          echo "PR Number: $PR_NUMBER"

      - name: Checkout swiftlang/swift-evolution-metadata-extractor
        uses: actions/checkout@v4
        with:
          repository: swiftlang/swift-evolution-metadata-extractor
          ref: main
          path: seme

      - name: Show Swift version
        run: swift --version

      - name: Build swift-evolution-metadata-extractor (release)
        run: swift build -c release
        working-directory: seme

      - name: Validate proposals
        run: ${{ github.workspace }}/seme/.build/release/swift-evolution-metadata-extractor validate --pull-request ${{ github.event.number }}
