name: Validate proposals with swift-evolution-metadata-extractor

on:
  pull_request:
    branches:
      - main

jobs:
  run-swift-evolution-metadata-extractor:
    name: Validate proposals with swift-evolution-metadata-extractor
    runs-on: macos-latest
    steps:
      - name: Checkout md-proposals
        uses: actions/checkout@v4

      - id: files
        uses: hanseltimeindustries/get-changed-files@v1
        with:
          filter: 'proposals/**/*'

      - name: Create list of full paths
        id: paths
        run: |
            paths=(${{ steps.files.outputs.added_modified }})
            filepaths=()
            for filepath in paths
            do
                filepaths+=("${{ github.workspace }}/$filepath")
                echo $filepaths
            done
            echo "filepaths=$filepaths" >> $GITHUB_OUTPUT

      - name: Checkout dempseyatgithub/swift-evolution-metadata-extractor (validation-reports)
        uses: actions/checkout@v4
        with:
          repository: dempseyatgithub/swift-evolution-metadata-extractor
          ref: validation-reports
          path: seme

      - name: Show Swift version
        run: swift --version

      - name: Build swift-evolution-metadata-extractor (release)
        run: swift build -c release
        working-directory: seme

      - name: Test full path action output
        run: echo ${{ steps.paths.outputs.filepaths }}

      - name: Validate proposals
        run: ${{ github.workspace }}/seme/.build/release/swift-evolution-metadata-extractor validate --base-path ${{ github.workspace }} ${{ steps.files.outputs.added_modified }}
